#!/bin/bash
# Global git commit-msg hook to prevent emoji and typographic dashes in commit messages

COMMIT_MSG_FILE="$1"

if [ ! -f "$COMMIT_MSG_FILE" ]; then
    echo "ERROR: Commit message file not found: $COMMIT_MSG_FILE"
    exit 1
fi

perl -CS -e '
# Unicode ranges for emoji
my $emoji_re = qr/[\x{1F600}-\x{1F64F}]|[\x{1F300}-\x{1F5FF}]|[\x{1F680}-\x{1F6FF}]|[\x{1F700}-\x{1F77F}]|[\x{1F780}-\x{1F7FF}]|[\x{1F800}-\x{1F8FF}]|[\x{1F900}-\x{1F9FF}]|[\x{1FA00}-\x{1FA6F}]|[\x{1FA70}-\x{1FAFF}]|[\x{2600}-\x{26FF}]|[\x{2700}-\x{27BF}]|[\x{231A}-\x{231B}]|[\x{23E9}-\x{23EC}]|[\x{23F0}]|[\x{23F3}]|[\x{25FD}-\x{25FE}]|[\x{2614}-\x{2615}]|[\x{2648}-\x{2653}]|[\x{267F}]|[\x{2693}]|[\x{26A1}]|[\x{26AA}-\x{26AB}]|[\x{26BD}-\x{26BE}]|[\x{26C4}-\x{26C5}]|[\x{26CE}]|[\x{26D4}]|[\x{26EA}]|[\x{26F2}-\x{26F3}]|[\x{26F5}]|[\x{26FA}]|[\x{26FD}]|[\x{2705}]|[\x{270A}-\x{270B}]|[\x{2728}]|[\x{274C}]|[\x{274E}]|[\x{2753}-\x{2755}]|[\x{2757}]|[\x{2795}-\x{2797}]|[\x{27B0}]|[\x{27BF}]|[\x{2B1B}-\x{2B1C}]|[\x{2B50}]|[\x{2B55}]/;

# Typographic dashes: en dash (U+2013), em dash (U+2014), horizontal bar (U+2015),
# and mathematical minus (U+2212)
my $dash_re = qr/[\x{2013}-\x{2015}]|\x{2212}/;

my @lines;
my $n = 0;
while (<STDIN>) {
    chomp;
    $n++;
    next if /^#/;   # Comment lines Git adds for the editor view
    push @lines, [$n, $_];
}

sub scan {
    my ($re) = @_;
    my @hits;
    for my $pair (@lines) {
        my ($num, $c) = @$pair;
        while ($c =~ /($re)/g) {
            push @hits, [$num, $c, pos($c) - length($1), $1];
        }
    }
    return @hits;
}

my @emoji_hits = scan($emoji_re);
my @dash_hits  = scan($dash_re);

if (@emoji_hits) {
    print "ERROR: Emoji found in commit message!\n";
    print "Emoji are not allowed in commit messages. Please remove them.\n\n";
    for my $h (@emoji_hits) {
        my ($num, $c, $at, $ch) = @$h;
        print "Line $num: $c\n";
        print "         " . (" " x $at) . "^ Emoji found at position $at: $ch\n\n";
    }
}

if (@dash_hits) {
    print "ERROR: Typographic dash found in commit message!\n";
    print "Non-standard dashes are not allowed. Use a plain hyphen instead.\n\n";
    for my $h (@dash_hits) {
        my ($num, $c, $at, $ch) = @$h;
        print "Line $num: $c\n";
        print "         " . (" " x $at) . "^ Typographic dash found at position $at: $ch\n\n";
    }
}

if (@emoji_hits || @dash_hits) {
    print "Commit aborted due to emoji/typographic dash detection in commit message.\n";
    print "Edit your commit message: remove all emoji and replace typographic dashes with a plain hyphen.\n";
    exit 1;
}

exit 0;
' < "$COMMIT_MSG_FILE"
